### PR TITLE
Set --enable-source-maps when testing.

### PR DESCRIPTION
**Pull request by rictic**

### CODE REVIEW

**Review by aomarks — CHANGES_REQUESTED** [review]
I believe this is built in to Node now with the [`--enable-source-maps`](https://nodejs.org/api/cli.html#--enable-source-maps) flag, so we can instead put:

`NODE_OPTIONS=--enable-source-maps` in front of each test command.

**Comment by rictic** [comment]
Wow, it's built into node? That's great!

**Comment by aomarks** [comment]
> Wow, it's built into node? That's great!

Ugh, it crashes Node 14 because the flag isn't recognized, and Windows because Windows has a different syntax for environment variables.

Maybe we just set this variable using `env` at the top of the GitHub Actions workflow (unless Node 14), and then we personally just put it in our `.bashrc` files?

**Comment by aomarks** [comment]
> Ugh, it crashes Node 14 because the flag isn't recognized, and Windows because Windows has a different syntax for environment variables.
> 
> Maybe we just set this variable using `env` at the top of the GitHub Actions workflow (unless Node 14), and then we personally just put it in our `.bashrc` files?

Alternatively, we could use https://github.com/kentcdodds/cross-env which works on Windows.

I wonder if this should be a Wireit feature, it would be very easy to implement something like `{"env": {"foo":"bar"}}`.

**Comment by aomarks** [comment]
> I wonder if this should be a Wireit feature, it would be very easy to implement something like `{"env": {"foo":"bar"}}`.

Would pair well with https://github.com/google/wireit/issues/66

**Review by aomarks — APPROVED** [review]

**Pull request merged**
