### PR TITLE
Re-Added Unhandled Exception Handling

### PR DESCRIPTION
**Pull request by ObliviousHarmony**
In https://github.com/google/wireit/pull/471 the handling of unhandled exceptions was removed. This adds that missing handling back so that any exceptions that aren't caught can be gracefully handled and raised to the user correctly.

### CODE REVIEW

**Review by aomarks — CHANGES_REQUESTED** [review]
Looks good! Mind just adding a changelog entry for this?

**Comment by aomarks** [comment]
Also needs an `npm run format`

**Review by aomarks — APPROVED** [review]

**Comment by aomarks** [comment]
> Looks good! Mind just adding a changelog entry for this?
> Also needs an npm run format

I added these, merging 👍

**Comment by ObliviousHarmony** [comment]
Thanks @aomarks, I missed the changelog and am too used to the Prettier ESLint plugin :smile: Odd looking test failure though.

**Pull request merged**
