### PR TITLE
Release 0.6.0

### PR DESCRIPTION
**Pull request by aomarks**

### CODE REVIEW

**Comment by AndrewJakubowicz** [comment]
Failing tests: "--npm·WARN·config·global·`--global`,·`--local`·are·deprecated.·Use·`--location=global`·instead."

**Comment by augustjk** [comment]
> Failing tests: "--npm·WARN·config·global·`--global`,·`--local`·are·deprecated.·Use·`--location=global`·instead."

https://github.com/npm/cli/issues/4980

I think we need the windows runners to use the latest version of npm cli with the fix.

**Comment by aomarks** [comment]
This should be good to go, PTAL

**Review by augustjk — APPROVED** [review]
🚀

**Review by AndrewJakubowicz — APPROVED** [review]

**Review by AndrewJakubowicz — APPROVED** [review]

**Pull request merged**
